### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by xaclincoln** [Ekhoo/Device#10]
when run carthage update, the carthage complains build error:

*** Skipped building Device due to the error:
Dependency "Device" has no shared framework schemes
If you believe this to be an error, please file an issue with the maintainers at https://github.com/Ekhoo/Device/issues/new

**Comment by Ekhoo** [comment]
fixed in #11

**Comment by Ekhoo** [comment]
I will build a new release today. I close the issue. :)

**Comment by Ekhoo** [comment]
Here is the fix => https://github.com/Ekhoo/Device/releases/tag/0.0.7
