### ISSUE TITLE
iPad 8th gen (10.2 inch) not recognized

### ISSUE THREAD

**Issue by castout1971** [Ekhoo/Device#104]
Device.size() returns unknownSize for iPad 8th gen 10.2 inch

**Comment by kishorepran** [comment]
Hello @castout1971 : Can you please check our latest release 3.3.0 via SPM and let me know if it works.

**Comment by kishorepran** [comment]
Hello @castout1971 : Updated cocoapods to 3.3.0 as well. Please re-open this ticket in case of any issue and tag me here thanks.
