### ISSUE TITLE
Support for iPad mini (5th Generation)

### ISSUE THREAD

**Issue by LeonardoXUI** [Ekhoo/Device#109]
Added a fue lines of code to support the iPad mini 5:

In `version.swift` added:

`case iPadMini5`

In `device.swift` added:

`case "iPad11,1", "iPad11,2":                        return .iPadMini5`

**Comment by 417-72KI** [comment]
It seems to be resolved in #106 , but hasn't be released yet 😂

Here is a workflow to use a resolved commit.
https://github.com/Ekhoo/Device/issues/105#issuecomment-802579617

**Comment by kishorepran** [comment]
The above pr has been merged and is available with SPM. Cocoapods update will follow soon. let me know for anything else.
