### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by fmessina** [Ekhoo/Device#111]
Hi!

Given the number of issues open and the absence of support for the last iOS devices (iPhone 13), I wanted to ask if this project is still being maintained?

**Comment by sealedace** [comment]
same question here...

**Comment by Droppix** [comment]
same question, please add iphone 13...

**Comment by sugitatestblue** [comment]
@Ekhoo

**Comment by sugitatestblue** [comment]
https://github.com/ptrkstr/Devices

**Comment by sugitatestblue** [comment]
But it is not compatible.

**Comment by sugitatestblue** [comment]
@[Ekhoo](https://github.com/Ekhoo)
are you here?
or anyone update?

**Comment by sugitatestblue** [comment]
or anyone fork

**Comment by Ekhoo** [comment]
Hello guys, a new collaborator have been added (https://github.com/kishorepran). The project will updated soon. Sorry for the delay.

**Comment by Ekhoo** [comment]
@ozgur do you want to be a collaborator as well?

**Comment by kishorepran** [comment]
Hello @Ekhoo : Can you please add me as an owner to the pod trunk as well. 
This will help me to update the spec for cocoapods as well for 3.3.0
Steps:
1. Register your trunk session by : pod trunk register me@lucas-ortis.com 'Lucas Ortis' --description='macbook pro'
2. Click the email to verify session.
3. pod trunk add-owner Device kishorepran@gmail.com
Thanks

**Comment by Ekhoo** [comment]
@kishorepran Done :)

**Comment by kishorepran** [comment]
Thanks @Ekhoo for your support. I am closing this issue guys.
I will be checking this section every week for updates and request.
Please feel free to reach out directly via my email / LinkedIn mentioned in this thread for anything urgent thanks.
LinkedIn: https://www.linkedin.com/in/pran-kishore/

**Comment by ozgur** [comment]
@Ekhoo I would love to.
