### ISSUE TITLE
3.4.0 is not released?

### ISSUE THREAD

**Issue by shimastripe** [Ekhoo/Device#121]
I hope cut the version to use of these great PRs!

- #115 
- #118

**Comment by kishorepran** [comment]
Hey Hi @shimastripe, thanks for asking. I am back from vacation 22nd Jun does that work. In the mean time will ask @shankywave1 if he is available.

**Comment by shimastripe** [comment]
Thanks to @kishorepran ! Will you be able to release it afterwards?

**Comment by kishorepran** [comment]
Hi, @shimastripe  released update to both SPM and Cocoa pods. let me know in case of any issues.

Pod Logs below
Cheers
Pran
-----------
 🎉  Congrats

 🚀  Device (3.4.0) successfully published
 📅  July 5th, 21:42
 🌎  https://cocoapods.org/pods/Device
 👍  Tell your friends!
