### ISSUE TITLE
Podspec deployment target needs to updated

### ISSUE THREAD

**Issue by glm4** [Ekhoo/Device#123]
Currently, the podspec specify the deployment target to iOS 8.0. 

For other Cocoapods libraries, if you have `Device` as a dependency pod, your library will not lint correctly your podspec using Xcode 14.3 and up. Please refer to [this issue](https://github.com/CocoaPods/CocoaPods/issues/11895) on Cocoapods.
So far there is no way to specify custom deployment targets for dependencies with the Podspec syntax, so this should be resolved by each pod podspec.

_This is not a problem if you install the dependency via SPM or directly into your project via cocoapods_

**Comment by kishorepran** [comment]
@glm4 : will updating the pod spec to 9.0 suffice...? If yes I will raise a pr > add you for review> release a minor version. let me know thanks.

**Comment by glm4** [comment]
Hi @kishorepran!
Unfortunately no 😢 
Xcode 14.3 ony supports from iOS 11 and up.
It is a limitation for Device doing this update?

**Comment by kishorepran** [comment]
hi @glm4 . I am not sure. Will need to check. by default I want to keep the min version possible. Let me give this a try tomorrow.

**Comment by ozgur** [comment]
same issue for carthage as well.

**Comment by kishorepran** [comment]
Guys can you please review my pr will merge and release version ASAP
@glm4: sorry for delay 
@ozgur : Is it possible for you to check with my branch for Carthage. thanks for your support.

**Comment by glm4** [comment]
@kishorepran LGTM
