### ISSUE TITLE
Privacy Manifest?

### ISSUE THREAD

**Issue by nokiaowner** [Ekhoo/Device#127]
Hello, At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does Device need to include this manifest?
Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

Here’s some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by kishorepran** [comment]
Hey hi, Thanks @nokiaowner for reaching out and pointing this.
I am responsible for maintaining device and will need to do a deep dive into the SDK and look if we do really need this.

sharing a tentative timeline:
1. check if wee need the privacy manifest and reply here. By Dec end
2. if we need it deploy a version by Jan 2nd week or with Xcode 15.1 support. which is ever is later.

**Comment by nokiaowner** [comment]
Hello,

Any update on this?

Thanks

**Comment by kishorepran** [comment]
Hi @nokiaowner : thanks for the reminder.
I would like to confirm that our SDK is not using any privacy required reason API as listed [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).
Please let me know for any more concerns, if not I will close this issue thanks.
