### ISSUE TITLE
Add shorcut isPad, isPhone, isPod

### ISSUE THREAD

**Issue by PGLongo** [Ekhoo/Device#18]
First of all, **thanks** for this pod.

A lot of times I want to check if the current device is of a specific type and I think it would be easier doing 

```swift
 if(Device.isPad()) //instead of  if (Device.type() == .iPad) 
```

So what do you think if I create a PR with the following code?

```swift
    static public func isPad() -> Bool {
        return Device.type() == .iPad
    }
    
    static public func isPhone() -> Bool {
        return Device.type() == .iPhone
        
    }
    
    static public func isPod() -> Bool {
        return Device.type() == .iPod
    }
```

**Comment by Ekhoo** [comment]
Yes if you want you can add thoses shortcuts :) I will release a new version with your changes :)

**Comment by Ekhoo** [comment]
Hello @PGLongo I have merged your PR and a new version is available :) Thank you a lot ! And sorry to be so slow to merge your work...

**Comment by PGLongo** [comment]
Thanks to you. I think that you have a lot of works as all the people here!
