### ISSUE TITLE
4" screen size missing

### ISSUE THREAD

**Issue by jyounus** [Ekhoo/Device#3]
Hey there,

Thanks for this library. Noticed something wrong with it, line 71: https://github.com/Ekhoo/Device/blob/master/Source/Device.swift#L71

I think that should be returning the Size.Screen4Inch enum.

**Comment by Ekhoo** [comment]
Oh yes ! Thank you very much ! I will release a fix tomorow !

**Comment by Ekhoo** [comment]
Hello @jyounus, Device [0.0.3](https://github.com/Ekhoo/Device/releases/tag/0.0.3) is out, with the 4 screen inch case fix.
