### ISSUE TITLE
1.1.0 is not compatible with 1.0.3

### ISSUE THREAD

**Issue by RyogaK** [Ekhoo/Device#30]
Carthage's operator `~>` means 
the version equals or later than right-hand version **which is compatible with that**
And also, this rule from the semantic versioning. http://semver.org/

If you can follow this rule, It's better to version as 2.0.0 because 1.1.0 is just supporting Swift3 and Swift3 is not compatible with Swift2.3 (1.0.3 or earlier).

In other word, if we wrote `github "Ekhoo/Device" ~> 1.0.3`, we can't build the library without changes of our codes.

**Comment by Ekhoo** [comment]
Ok I will build release a new version as soon as possible. Thank you :)

**Comment by Ekhoo** [comment]
Device `2.0.0` is available :)

**Comment by RyogaK** [comment]
@Ekhoo Hi, thanks for make release 2.0.0. But you didn't remove 1.1.0, so we still can't build.
Could you remove release 1.1.0?

**Comment by Ekhoo** [comment]
Done :)
