### ISSUE TITLE
Swift 2.3 compatibility?

### ISSUE THREAD

**Issue by carmelogallo** [Ekhoo/Device#33]
Hey guys, could be possible to have the compatibility with Swift 2.3?

**Comment by mitchellporter** [comment]
I'm going to submit a fork for this over the weekend. There's no reason we can't maintain a `swift 2.3` branch and update for the iPhone 7 devices as well.

**Comment by Ekhoo** [comment]
The iPhone 7 is handled. I haven't the time to make a swift 2.3 compliant branch. So if you want I can create a specific branch and you can send a PR on it.

**Comment by cikpis** [comment]
Sure! I've already done it so I just need to do the PR.

**Comment by Ekhoo** [comment]
Here is the branch => https://github.com/Ekhoo/Device/tree/swift_2_3 :)

**Comment by saltwat5r** [comment]
But it's still Swift 3.0 code at this branch

**Comment by saltwat5r** [comment]
I've already created PR #34

**Comment by Ekhoo** [comment]
Merged 👍
