### ISSUE TITLE
Suggestion for more helper functions

### ISSUE THREAD

**Issue by jyounus** [Ekhoo/Device#4]
Hey,

I think it would be really useful (for me at least) if we could have some extra helper functions that simply return either true or false. A function that returns true if the current device is either a 4inch or below etc. 

Of course I can just write them myself in my project, but thought it might be useful if they were part of this lib. What do you think?

**Comment by Ekhoo** [comment]
Ok no problem I will add this helper functions this week ! Thank you for your proposal :)

**Comment by jyounus** [comment]
Awesome! :D

**Comment by Ekhoo** [comment]
what do you think about:
- `isEqualToScreenSize({Size})`
- `isLargerThanScreenSize({Size})`
- `isSmallerThanScreenSize({Size})`

Will it be enought for you ?

**Comment by jyounus** [comment]
That would be perfect for my needs. Can't think of a more elegant way to do this. :)

**Comment by Ekhoo** [comment]
Thank you :) I will release a new version as soon as possible this week.

**Comment by Ekhoo** [comment]
@jyounus here is the [0.0.4](https://github.com/Ekhoo/Device/releases/tag/0.0.4) version of Device with the helpers :)

**Comment by jyounus** [comment]
Perfect, thank you! :D


Btw, I noticed a small error in the readme helper function sample code:

```
if Device.isEqualToScreenSize(Size.Screen4Inch) {
    print("It's a 5.5 inch screen")
}
```

That string should print "4 inch" instead of "5.5 inch". ;)

**Comment by Ekhoo** [comment]
Oh yes thank you :) Fixed :+1:
