### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by sebyddd** [Ekhoo/Device#5]
The original [SDVersion](https://github.com/sebyddd/SDVersion/) library is protected under [MIT License](https://raw.githubusercontent.com/sebyddd/SDVersion/master/LICENSE).

I kindly ask you to change the logo and the description as you do not posses permission to use them on your behalf.

Regards,
Sebastian

**Comment by Ekhoo** [comment]
No problem, I will change it as soon as possible.

**Comment by sebyddd** [comment]
Thank you. Also, please include the reference to the original library in the License section.

**Comment by Ekhoo** [comment]
Done
