### ISSUE TITLE
Add iPhone X

### ISSUE THREAD

**Issue by tbaranes** [Ekhoo/Device#51]

**Comment by Sweefties** [comment]
started here : https://github.com/Sweefties/Device/commit/9942a260dfeadf1410d15ada0d69ea90b4be531f

**Comment by Ekhoo** [comment]
Hello, can you send a PR ?

**Comment by Sweefties** [comment]
Done #53

**Comment by Ekhoo** [comment]
@Sweefties thanks a lot ! Here is the new release [3.0.3](https://github.com/Ekhoo/Device/releases/tag/3.0.3)
