### ISSUE TITLE
Does "iPhone4,2", "iPhone4,3" exist?

### ISSUE THREAD

**Issue by takecian** [Ekhoo/Device#54]
I could not find "iPhone4,2", "iPhone4,3" https://www.theiphonewiki.com/wiki/Models and other tech blogs.
Does "iPhone4,2", "iPhone4,3" exist?

**Comment by kishorepran** [comment]
@takecian : Both iPhone 4 and 4S are supported. Closing this issue. do let me know of you still run into issues.
