### ISSUE TITLE
Cannot install 3.0.3 via cocoapod

### ISSUE THREAD

**Issue by umekun123** [Ekhoo/Device#59]
When I install 3.0.3, I get this error.

[!] Unable to satisfy the following requirements:
- `Device (~> 3.0.3)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `Device (~> 3.0.3)`.

I can only install it up to 3.0.2, any idea to fix this?

**Comment by pschneider** [comment]
Did you run `pod repo update` or `pod install --repo-update` already? Installing `3.0.3` after updating the CocoaPods Master Repo works just fine for me.

**Comment by kishorepran** [comment]
Closing this issue as cocoapods works for version 3.2.1
