### ISSUE TITLE
iPad Recognition

### ISSUE THREAD

**Issue by CalebKierum** [Ekhoo/Device#61]
This framework cannot currently recognize iPad Minis

Additionally it cannot differentiate between the new Gen 2 iPad Pros. The classification information in the iPad pro section conflicts with other reports of what they should be.

**Comment by kishorepran** [comment]
Hello @CalebKierum : Please check out our latest release 3.3.0 on SPM / Carthage / Cocoa pods. Please tag me here in this ticket for any issues.
Thanks
