### ISSUE TITLE
iPhone Xs, Xs Max, Xʀ + iPad (6th gen.) + Swift 4

### ISSUE THREAD

**Issue by Sweefties** [Ekhoo/Device#66]
@Ekhoo  Started here: https://github.com/Sweefties/Device/commit/7e7f025d6895b0acb9f2c36f881dd307b71ebfdf & https://github.com/Sweefties/Device/commit/c6da20eaa00405ca1f3067e0e6a4966fac127fd5

wait for checks (models identifiers)..

**Comment by Sweefties** [comment]
PR #68

**Comment by andmix** [comment]
Good job, man

> @Ekhoo Started here: [Sweefties@7e7f025](https://github.com/Sweefties/Device/commit/7e7f025d6895b0acb9f2c36f881dd307b71ebfdf) & [Sweefties@c6da20e](https://github.com/Sweefties/Device/commit/c6da20eaa00405ca1f3067e0e6a4966fac127fd5)
> 
> wait for checks (models identifiers)..



> @Ekhoo Started here: [Sweefties@7e7f025](https://github.com/Sweefties/Device/commit/7e7f025d6895b0acb9f2c36f881dd307b71ebfdf) & [Sweefties@c6da20e](https://github.com/Sweefties/Device/commit/c6da20eaa00405ca1f3067e0e6a4966fac127fd5)
> 
> wait for checks (models identifiers)..

good job, man

**Comment by andmix** [comment]
good job, man

**Comment by pgawlowski** [comment]
Podspec bumped? Cause I can not update lib using pod update :(

**Comment by Sweefties** [comment]
@pgawlowski see https://github.com/Ekhoo/Device/pull/69#issuecomment-424237762 or use : `pod 'Device', :git => 'https://github.com/Sweefties/Device.git', :branch => 'master'` to your podfile

**Comment by pgawlowski** [comment]
I know but this is more like workaround ... :( That is negation of cocoa purpose.

**Comment by Ekhoo** [comment]
Device v3.1.2 available.

**Comment by Ekhoo** [comment]
[Device v3.1.2](https://cocoapods.org/pods/Device) is available.
