### ISSUE TITLE
Update podspec to 3.1.2

### ISSUE THREAD

**Issue by maurovc** [Ekhoo/Device#70]
So cocoapods downloads the version 3.1.0 of the library without all the latest changes as the version specified in the podspec is 3.1.0 and not 3.1.2

**Comment by dvluong** [comment]
Running into this as well.

**Comment by romansorochak** [comment]
same issue

**Comment by thihaaung6245** [comment]
@Ekhoo , please provide this ASAP. Thanks

**Comment by Ekhoo** [comment]
[Device v3.1.2](https://cocoapods.org/pods/Device) available.
