### ISSUE TITLE
Add new iPad Pro 2018 (fall - 11"/12.9") + simulator improvements

### ISSUE THREAD

**Issue by Sweefties** [Ekhoo/Device#73]
PR here: https://github.com/Ekhoo/Device/pull/74

**Comment by floriangbh** [comment]
@Ekhoo Any chance to merge this ? :)

**Comment by Quailcreek** [comment]
I see that iPad 11 was supposedly added awhile ago. I have 3.1.2 installed and I don't see the 11 and a choice. Am I doing something wrong? Is anybody else able to see it?

**Comment by kishorepran** [comment]
New devices have been added to our version 3.3.0 supported via SPM. Cocoapods update will follow soon.
