### ISSUE TITLE
VIDEO TUTORIAL ON YOUTUBE

### ISSUE THREAD

**Issue by rebeloper** [Ekhoo/Device#78]
Hi,

I love your repo so much that I have created a YouTube video tutorial on it:

https://www.youtube.com/watch?v=cTZcOaGgD-E

Feel free to add it to the README with the following image (people click on images more often than simple links) 

![detect current device type in swift easy thubmnail](https://user-images.githubusercontent.com/2488011/53433240-ba33a780-39fc-11e9-820b-9e1017adce18.png)

Keep up the good work :)

**Comment by kishorepran** [comment]
@rebeloper : Wow your you tube video is great. You will have this link in readme with the image for sure. by next weekend. let me know if there's is anything else I could support you with thanks.

**Comment by kishorepran** [comment]
@shankywave1 Can you include this in your release as well

**Comment by kishorepran** [comment]
@rebeloper : this is done. thanks. sorry for the delay. would love to continue contributing. please reach out to me in case you have any more ideas that you need help with. thanks.

**Comment by rebeloper** [comment]
Nice, thanks!
