### ISSUE TITLE
Carthage compatibility

### ISSUE THREAD

**Issue by sprint84** [Ekhoo/Device#8]
Can you add Carthage compatibility?

Thanks

**Comment by Ekhoo** [comment]
Hello @sprint84 `Device` should work with `Carthage`. Look at the ReadMe file to see the instructions.

**Comment by sprint84** [comment]
*** Skipped building Device due to the error:
Dependency "Device" has no shared framework schemes

**Comment by Ekhoo** [comment]
Ok @sprint84 I will fix it as soon as possible. Thank you !

**Comment by mrkeithelliott** [comment]
I think you just need to make your scheme shared

**Comment by Ekhoo** [comment]
Here is the fix => https://github.com/Ekhoo/Device/releases/tag/0.0.7
