### ISSUE TITLE
Xcode 11 SPM: Device has no Package.swift manifest for version 3.1.2

### ISSUE THREAD

**Issue by RamblinWreck77** [Ekhoo/Device#83]
Pretty much the title. Trying to migrate from Cocoapods -> SPM, looks like all we need is the manifest file.

**Comment by RamblinWreck77** [comment]
@Ekhoo Sorry to bother you, but would it be possible to push a new release with a Package.swift file? From what I can tell this library will work just fine with Swift Package Manager, it just needs a 5 line manifest file to tell SPM what it's called.

**Comment by sugitatestblue** [comment]
SPM no supported?

**Comment by kishorepran** [comment]
Hi, Support for SPM has been added for version 3.3.0 with updated device list. let me know for anything else.
